### ISSUE TITLE
Add duty complete weekly unlock Condition tag to party listing

### ISSUE THREAD

**Issue by Gasteno** [zeroeightysix/remote-party-finder#1]
Hi and thanks for keeping this plugin alive. This isn't a big deal now, but whenever you get the chance it would be great to add the duty complete (weekly reward unclaimed) condition tag to the party listing of the website. Savage is currently unlocked atm so not a big deal, but will be nice once xpac rolls through and the new savage tier becomes available.

thanks!!

**Comment by zeroeightysix** [comment]
Thank you the kind words and report!

Provided I don't forget to deploy it by the time DT releases, we should have this now :slightly_smiling_face:

**Comment by Gasteno** [comment]
You are so awesome. Thx!
