### ISSUE TITLE
Skip private pf

### ISSUE THREAD

**Issue by Infiziert90** [zeroeightysix/remote-party-finder#3]
The plugin shouldn't list private entries, as they aren't really meant for the public. 
It is also currently impossible to filter them as nothing on the website exposes this flag.

An easy implementation would be at plugin level with a check like this 
```cs
    private void OnListing(PartyFinderListing listing, PartyFinderListingEventArgs args) {
        if (listing[SearchAreaFlags.Private]) {
            // Exclude private entries
            return;
        }
        
        if (!this.Batches.ContainsKey(args.BatchNumber)) {
            this.Batches[args.BatchNumber] = new List<PartyFinderListing>();
        }

        this.Batches[args.BatchNumber].Add(listing);
    }
```

**Comment by zeroeightysix** [comment]
That's strange, the server is actually supposed to filter them:

https://github.com/zeroeightysix/remote-party-finder/blob/fb5198b9113b4659009da8a248cdb4f6d1fd1e58/server/src/web.rs#L273-L274

I'll look into it

**Comment by zeroeightysix** [comment]
Sorry, but I can't reproduce. It seems like private PFs are being filtered correctly on the website.

Could you share an example of it working incorrectly?

**Comment by Infiziert90** [comment]
Last time i noticed this was with discord bots that use xivpf, showing private PFs that shouldn't be listed at all
Could it be some flag combination that the website doesn't filter correctly?

**Comment by Infiziert90** [comment]
Haven't been able to repro myself atm, thanks for looking into it !
