### ISSUE TITLE
Party finder created by users on new Worlds

### ISSUE THREAD

**Issue by Gasteno** [zeroeightysix/remote-party-finder#5]
I think there might  be an issue with players creating PF entries when their home wolrd is one of the new  worlds that were added recently. It seems to have their name @ and then a number of the remote party site.

**Comment by zeroeightysix** [comment]
You're right, the release of the new worlds flew under my radar due to my exams. I'll be fixing this shortly - thanks for letting me know.

**Comment by Gasteno** [comment]
> You're right, the release of the new worlds flew under my radar due to my exams. I'll be fixing this shortly - thanks for letting me know.

Education always comes first. Thanks for all that you do and good luck on your exams!!

**Comment by Gasteno** [comment]
it looks like this is resolved thx!
