### ISSUE TITLE
7.05 deploy

### ISSUE THREAD

**Issue by Gasteno** [zeroeightysix/remote-party-finder#8]
any news on  when 7.05 update will get deployed? Duty are still saying HighEndDuty atm. Thx for all that you do!

**Comment by zeroeightysix** [comment]
Hi! I just deployed it. I was on vacation earlier, and couldn't get the cross-build to work on my laptop. My apologies for the delay!

**Comment by Gasteno** [comment]
> Hi! I just deployed it. I was on vacation earlier, and couldn't get the cross-build to work on my laptop. My apologies for the delay!

Ty!! Hope you had or are enjoying that time off. Take care.
